# -*- coding: utf-8 -*-
"""Data-Rent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12XV7sRRBeu_IwdaZbmrt7maC6oT95E8p
"""

import streamlit as st
import pandas as pd

# Load data from GitHub CSV
csv_url = "https://github.com/Pritesh-Lathiya/Office/blob/main/Data-Rent.csv"
df = pd.read_csv(csv_url)

# Page title
st.title("🏢 Office Rental Finder")

# Sidebar filters
st.sidebar.header("Filter by Square Feet")
min_sqft = int(df['SQ FT'].min())
max_sqft = int(df['SQ FT'].max())

sqft_range = st.sidebar.slider("Select Range", min_value=min_sqft, max_value=max_sqft, value=(min_sqft, max_sqft))

# Filter data
filtered_df = df[(df['SQ FT'] >= sqft_range[0]) & (df['SQ FT'] <= sqft_range[1])]

# Show number of results
st.success(f"{len(filtered_df)} office(s) match your filter.")

# Display results
for index, row in filtered_df.iterrows():
    with st.expander(f"📍 {row['PROPERTY ADDRESS']} - {row['AREA']} ({row['SQ FT']} sq ft)"):
        st.write(f"**Rent:** ₹{row['RENT']}")

        # Convert message to rich text
        st.markdown(f"**Details:**<br>{row['MESSAGE']}", unsafe_allow_html=True)

        # Show photo link
        if pd.notna(row['PHOTOS']) and row['PHOTOS'].startswith("http"):
            st.markdown(f"[📷 View Photos]({row['PHOTOS']})", unsafe_allow_html=True)
